//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ani.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingEntry
    {
        public int Id { get; set; }
        public int RatingId { get; set; }
        public int UserId { get; set; }
        public int Rating { get; set; }
        public System.DateTime CreatedTimeUTC { get; set; }
        public System.DateTime ModifiedTimeUTC { get; set; }
        public System.DateTime EntryDateUTC { get; set; }
        public string Comments { get; set; }
    
        public virtual Rating Rating1 { get; set; }
        public virtual User User { get; set; }
    }
}
