//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ani.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNode
    {
        public int UN_ID { get; set; }
        public int UN_UserID { get; set; }
        public int UN_NodeID { get; set; }
        public System.DateTime UN_CreatedTimeUTC { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual User User { get; set; }
    }
}
