//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transit
    {
        public int TR_ID { get; set; }
        public int TR_StartLocID { get; set; }
        public int TR_EndLocID { get; set; }
        public Nullable<System.DateTime> TR_StartTimeUTC { get; set; }
        public Nullable<System.DateTime> TR_EndTimeUTC { get; set; }
        public Nullable<System.DateTime> TR_TargetStartTimeUTC { get; set; }
        public Nullable<System.DateTime> TR_TargetEndTimeUTC { get; set; }
        public System.DateTime TR_CreatedTimeUTC { get; set; }
        public System.DateTime TR_ModifiedTimeUTC { get; set; }
        public int TR_CreatorUserNodeID { get; set; }
        public int TR_ModifiedByNodeID { get; set; }
    
        public virtual GPSLocation GPSLocation { get; set; }
        public virtual GPSLocation GPSLocation1 { get; set; }
        public virtual Node Node { get; set; }
        public virtual UserNode UserNode { get; set; }
        public virtual User User { get; set; }
    }
}
