//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserNodes = new HashSet<UserNode>();
        }
    
        public int U_ID { get; set; }
        public string U_UserName { get; set; }
        public string U_FirstName { get; set; }
        public string U_LastName { get; set; }
        public string U_EmailAddress { get; set; }
        public Nullable<System.DateTime> U_LastActivityTimeUTC { get; set; }
        public System.DateTime U_CreatedTimeUTC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNode> UserNodes { get; set; }
    }
}
