//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeatherCode()
        {
            this.WeatherPredictions = new HashSet<WeatherPrediction>();
            this.WeatherRecords = new HashSet<WeatherRecord>();
        }
    
        public int WC_ID { get; set; }
        public string WC_Name { get; set; }
        public bool WC_HasRain { get; set; }
        public bool WC_HasClouds { get; set; }
        public bool WC_HasStorm { get; set; }
        public bool WC_HasWind { get; set; }
        public bool WC_HasSnow { get; set; }
        public int WC_SeverityID { get; set; }
        public string WC_IconClass { get; set; }
        public string WC_ImageUrl { get; set; }
    
        public virtual Severity Severity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherPrediction> WeatherPredictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherRecord> WeatherRecords { get; set; }
    }
}
