//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherRecord
    {
        public int ID { get; set; }
        public int ZipCode { get; set; }
        public int WeatherCode { get; set; }
        public int Temperature { get; set; }
        public string Description { get; set; }
        public System.DateTime RecordTimeUTC { get; set; }
        public System.DateTime CreatedDateUTC { get; set; }
        public int CreatedUserID { get; set; }
        public string Sunrise { get; set; }
        public string Sunset { get; set; }
        public int Humidity { get; set; }
        public int Visibility { get; set; }
        public double Pressure { get; set; }
        public int Rising { get; set; }
        public int WindChill { get; set; }
        public int WindDirection { get; set; }
        public int WindSpeed { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
        public int Source { get; set; }
    
        public virtual User User { get; set; }
        public virtual WeatherCode WeatherCode1 { get; set; }
        public virtual WeatherSource WeatherSource { get; set; }
        public virtual ZipCode ZipCode1 { get; set; }
    }
}
