//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public int ZIP_ID { get; set; }
        public string ZIP_Name { get; set; }
        public string ZIP_State { get; set; }
        public int ZIP_LocationID { get; set; }
    
        public virtual GPSLocation GPSLocation { get; set; }
    }
}
