//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattEland.Ani.AniServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficIncidentSeverity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrafficIncidentSeverity()
        {
            this.TrafficIncidents = new HashSet<TrafficIncident>();
        }
    
        public int TIS_ID { get; set; }
        public string TIS_Name { get; set; }
        public int TIS_SeverityID { get; set; }
    
        public virtual Severity Severity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrafficIncident> TrafficIncidents { get; set; }
    }
}
